---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  -  name: i want to install webserver1 on ubuntu
     apt:
       name: apache2
       state: present
     when: ansible_os_family =="Debian"

  -  name: i want to start webserver on ubuntu
     apt:
      name: apache2
      state: present
     when: ansible_os_family =="Debian"

  -  name: i want to install webserver1 on Redhat
     yum:
       name: httpd
       state: present
     when: ansible_os_family =="Redhat"

  -  name: i want to start webserver on redhat
     service:
      name: httpd
      state: started
     when: ansible_os_family =="Redhat"
